CREATE TABLE IF NOT EXISTS rotations (
  date TEXT PRIMARY KEY,
  lead TEXT NOT NULL,
  rest TEXT NOT NULL,
  supports_json TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS themes (
  week_start TEXT PRIMARY KEY,
  theme TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS settings (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS events (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  ts TEXT NOT NULL,
  kind TEXT NOT NULL,
  payload TEXT NOT NULL
);
