CREATE TABLE IF NOT EXISTS rotations (date TEXT PRIMARY KEY, lead TEXT, rest TEXT, supports_json TEXT);
CREATE TABLE IF NOT EXISTS themes (week_start TEXT PRIMARY KEY, theme TEXT);
CREATE TABLE IF NOT EXISTS settings (key TEXT PRIMARY KEY, value TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS events (id INTEGER PRIMARY KEY AUTOINCREMENT, ts TEXT, kind TEXT, payload TEXT);
CREATE TABLE IF NOT EXISTS sisters (name TEXT PRIMARY KEY, token TEXT, channel_id TEXT);
CREATE TABLE IF NOT EXISTS persona (name TEXT PRIMARY KEY, traits_json TEXT, bounds_json TEXT, last_update TEXT);
CREATE TABLE IF NOT EXISTS memories (id INTEGER PRIMARY KEY AUTOINCREMENT, sister TEXT, ts TEXT, kind TEXT, content TEXT);
CREATE TABLE IF NOT EXISTS feedback (id INTEGER PRIMARY KEY AUTOINCREMENT, ts TEXT, sister TEXT, signal TEXT, weight REAL DEFAULT 1.0);
